all:creat_sem remove_sem get_val_sem set_val_sem p_sem
creat_sem:
	gcc -o creat_sem creat_sem.c
remove_sem:
	gcc -o remove_sem remove_sem.c
get_val_sem:
	gcc -o get_val_sem get_val_sem.c
set_val_sem:
	gcc -o set_val_sem set_val_sem.c
p_sem:
	gcc -o p_sem p_sem.c
clean:
	rm creat_sem remove_sem get_val_sem set_val_sem p_sem

